version: "3.9"

services:
  proxyapp:
    build:
      context: .
      dockerfile: docker/proxy-pass/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - fullstack-fe
      - fullstack-be
    networks:
      fullstack-demo-app:
        aliases:
          - "proxy-pass"

  fullstack-fe:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile

  fullstack-be:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: "sh ./delay.sh"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 20
        window: 120s

  fullstack-db:
    volumes:
      - fullstack-data:/var/lib/mysql

volumes:
  fullstack-data:
