version: "3.9"

services:
  fullstack-fe:
    image: node:17-alpine3.15
    user: "node"
    container_name: fullstack-fe
    working_dir: /home/node/app
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "127.0.0.1:8080:8080"
    command: "yarn dev"
    networks:
      fullstack-demo-app:

  fullstack-be:
    image: node:17-alpine3.15
    user: "node"
    container_name: fullstack-be
    working_dir: /home/node/app
    environment:
      - NODE_ENV=$NODE_ENV
    volumes:
      - ./backend:/home/node/app
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - fullstack-db
    command: "tail -f /dev/null"
    networks:
      fullstack-demo-app:

  fullstack-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    container_name: $MYSQL_HOST
    restart: always
    ports:
      - 127.0.0.1:$MYSQL_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    healthcheck:
      test: mysql $MYSQL_DATABASE --user=$MYSQL_USER --password='$MYSQL_PASSWORD' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      fullstack-demo-app:

networks:
  fullstack-demo-app:
