version: "3.9"

x-env: &env
  environment:
    MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    MYSQL_DATABASE: $MYSQL_DATABASE
    MYSQL_USER: $MYSQL_USER
    MYSQL_PASSWORD: $MYSQL_PASSWORD
    MYSQL_HOST: $MYSQL_HOST
    MYSQL_PORT: $MYSQL_PORT

services:
  fullstack-fe:
    container_name: fullstack-fe
    environment:
      - NODE_ENV=$NODE_ENV
    networks:
      fullstack-demo-app:
        aliases:
          - "fe-app"

  fullstack-be:
    user: "node"
    container_name: fullstack-be
    working_dir: /home/node/app
    <<: *env
    depends_on:
      - fullstack-db
    networks:
      fullstack-demo-app:
        aliases:
          - "node-app"

  fullstack-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    container_name: $MYSQL_HOST
    restart: always
    <<: *env
    healthcheck:
      test: mysql $MYSQL_DATABASE --user=$MYSQL_USER --password='$MYSQL_PASSWORD' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      fullstack-demo-app:
        aliases:
          - "db-mysql"

networks:
  fullstack-demo-app:
