version: "3.9"

services:
  fullstack-fe:
    build: ${PWD}/docker/devel
    working_dir: /home/node/app
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "127.0.0.1:8080:8080"
    command: "tail -f /dev/null"

  fullstack-be:
    build: ${PWD}/docker/devel
    volumes:
      - ./backend:/home/node/app
    ports:
      - "127.0.0.1:3000:3000"
    command: "tail -f /dev/null"

  fullstack-db:
    ports:
      - 127.0.0.1:$MYSQL_PORT:3306
